### ISSUE TITLE
Issue with GPT

### ISSUE THREAD

**Issue by zdaar** [connery-io/connery#77]
Hello,

I followed the quickstart guide and added the gmail plugin to my runner on codespaces. I can curl the list of actions available just fine. However, the listActions action from the GPT fails.

This is the server side message on each call
`runner:start: {"type":"all-exceptions-filter","message":"Not Found"}`

I setup the gmail plugin, imported the openai spec from the public url that I set in the .env file, even reloaded the application

Convo looks like this :

User
Call the animated-acorn-6wx59x7xjfxrj5-4201.app.github.dev API with the listActions operation
GPT
```
[debug] Calling HTTP endpoint
{
  "domain": "public_url_for_runner_endpoint.app.github.dev",
  "method": "get",
  "path": "/v1/actions",
  "operation": "listActions",
  "operation_hash": "bc76b7c0609fe9f2e8d90b1b8f8c1ca67143ae14",
  "is_consequential": false,
  "params": {}
}
[debug] Response received
{
  "response_data": {
    "status": "error",
    "error": {
      "message": "Not Found"
    }
  },
  "status_code": 404,
  "action_id": "g-055aa64bda03bfd261d4cb28204cfa8a81be40a2"
}
```
curl works just fine 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   370  100   370    0     0   1371      0 --:--:-- --:--:-- --:--:--  1375
```
{
  "status": "success",
  "data": [
    {
      "id": "CPA71B593AD9761837C1CE4B0B9BDE99",
      "key": "connery-io/connery-runner-administration@main",
      "title": "Connery Runner Administration",
      "description": "This plugin provides actions to admin the Connery Runner."
    },
    {
      "id": "CP18CB26B78532324F668984C23418DE",
      "key": "connery-io/gmail@v1.0.2",
      "title": "Gmail",
      "description": "Gmail plugin for Connery"
    }
  ]
}
```

Any help appreciated, thanks

**Comment by machulav** [comment]
Hi @zdaar, thank you for the question!

I've just reproduced the issue by configuring the runner URL in the `.env` with the trailing slash like the following:

```
CONNERY_RUNNER_PUBLIC_URL=https://fuzzy-robot-vgw5v7r4xqfpr6-4201.app.github.dev/
```

In this case, I also receive the "Not Found" error in my GPT because the GPT requests to not existing URL: `https://fuzzy-robot-vgw5v7r4xqfpr6-4201.app.github.dev//v1/actions` (note `//`).

Then I removed the trailing slash from the URL, the request was successful in the GPT, and I got the list of actions.

Maybe this is the problem in your case as well?

Note that after changing the URL in `.env`, you have to restart the runner and reimport the OpenAPI specification into your GPT to update the URL in the OpenAPI specification.

I hope that helps.

**Comment by zdaar** [comment]
Thank you !! Its now working :)

**Comment by machulav** [comment]
Perfect! 

I've just added a comment to the `.env` file as a quick fix.
Later, we will have a proper validation when we store the configuration in the database and have the frontend to manage the runner.

**Comment by machulav** [comment]
@zdaar, may I ask you what use case you consider Connery for? And what has your experience been with Connery till now?
